server:
  servlet:
    context-path: /api-clean

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,mappings
  endpoint:
    health:
      show-details: always